muxinc/mux-node-sdk

- .travis.yml
- README.md
- src/base.js
- src/data/data.js
- src/data/resources/errors.js
- src/data/resources/exports.js
- src/data/resources/filters.js
- src/data/resources/metrics.js
- src/data/resources/video_views.js
- src/mux.js
- src/video/resources/assets.js
- src/video/resources/liveStreams.js
- src/video/resources/playbackIds.js
- src/video/video.js
- test/unit/base.spec.js
If you have the two environment variables `MUX_TOKEN_ID` and `MUX_TOKEN_SECRET` in your environment variables, you don't need to include them when you create a new class.
Also refactored a bit so I only needed to do this check in one place.
> Allow environment variables as a default

- README.md
- src/base.js
- src/mux.js
- Updates the user agent to be Mux Node and the version number
- Allows a configuration object to be passed into the base to make it easier to adjust the base url for testing, etc.
> Mux Node user agent and allow for an options config

- README.md
- src/mux.js
- src/webhooks/resources/verify_header.js
- src/webhooks/webhooks.js
- test/unit/mux.spec.js
- test/unit/webhooks/resources/verify_header.spec.js
- test/unit/webhooks/webhooks.spec.js
This is a first rough stab at this. So, feedback please <3.
I based this implementation entirely on the stripe sdk [source](https://github.com/stripe/stripe-node/blob/68da1c786405bee1f1bbe0bebba2ec6de0c34386/lib/Webhooks.js#L70)
Public API:
```javascript
const Mux = require('@mux/mux-node');
const { Webhooks } = Mux;
// returns `true` if verified otherwise throws one of four errors
Webhooks.verifyHeader(body, signature, secret);
```
~One note about this Public API implementation:~
* ~Technically for `Webhooks.verifyHeader` we don't need the `accessToken` and `secret`, so if we want, `Webhooks` could be static on the `Mux` variable, similar to how the JWT helper works. Because of #12 I thought in the future we would expose other functionality on `Webhooks` (for example `Webhooks.create` or …
> Add Mux.Webhooks.verifyHeader function

- src/video/resources/deliveryUsage.js
This fixes the import example to ensure the Video class is being imported instead of DeliveryUsage. Matches the convention of all other classes.
> Fix example to use Video instead of DeliveryUsage

- README.md
The Webhooks example has a try / catch block where the catch clause is duplicated. I removed one of them.
> Remove duplicated catch in webhooks example

- package.json
- test/integration/_helper.js
These env vars are requiring for running these integration tests. No real API requests are made, they are run against recorded requests.
Since these tests also get run in forks of this repo, we don't have access to any ENV vars that are set in TravisCI, so let's hard-code them here.
> Use hard-coded fake crendentials when running test:int

- types/interfaces/Asset.ts
The API doesn't always return a `master` property, so the Asset interface should mark the property as optional to ensure that consumers of the library appropriately handle the case where the `master` property is not present.
> Mark asset.master as optional

- README.md
The webhook example function had syntax issues, by a curly-brace missing
> Fix Syntax Issue and misrepresentation in webhook example

- README.md
Not sure if it was intentionally kept so in the documentation, feel free to reject if so. The example below was correct, but the explanation used capital casing which won't be a valid header Node/Express
> Documentation fix - Mux Signature with wrong casing

- types/mux.d.ts
Improve the typescript types of the `JWT.sign` method as suggested in issue #67 .
> Improve typescript types of JWT.sign method

- CHANGELOG.md
- package.json
Changes between this branch and v3.0.2 tag can be seen here:
https://github.com/muxinc/mux-node-sdk/compare/v3.0.2...dj/release-3-0-3
#69 is the only code change, all other changes were for documentation
> prep 3.0.3 release

- types/mux.d.ts
• mark 'type' as optional
• stronger type for 'type'
> Further improve typescript typings for 'Mux.JWT.sign()'

- src/mux.js
This is necessary for proper ES6-style importing. See: https://stackoverflow.com/questions/40294870/module-exports-vs-export-default-in-node-js-and-es6
I think this is the cause of #61.
> Provide a default export

- README.md
- src/utils/jwt.js
- test/unit/utils/jwt.spec.js
- types/mux.d.ts
Adheres to the docs as described in guide located at https://docs.mux.com/docs/storyboard-guide#are-signed-urls-supported.
Looks like prettier made a few add'l changes, let me know if this needs reformatted
> Allow storyboard signing

- types/mux.d.ts
Based on https://github.com/muxinc/mux-node-sdk/blob/master/src/video/resources/assets.js the parameter liveStreamId is incorrect on the deletePlaybackId function.
> Fix wrong parameter ins Assets.deletePlaybackId type

- package.json
- yarn.lock
Bump axios to 0.21.4 because of https://github.com/advisories/GHSA-cph5-m8f7-6c5x
> feat: bump axios from 0.21.1 to 0.21.4

- package.json
closes #134 and #130 
This is due to a regression in axios `0.21.2` where our response interceptor was not getting run (https://github.com/axios/axios/pull/4013)
diff: https://github.com/muxinc/mux-node-sdk/compare/v3.3.0...v3.3.1
> bump axios dep to ^0.21.4

- README.md
Update the docs given friction encountered following examples in the README
1. Replace usage of `request` with another request library in our example. Users can use whatever they prefer ➕ 
2. Explicitly require packages like `fs` and `dotenv` ➕ 
3. Make playback ID available to the consumer in one step instead of two ➕ 
There's no strong preference for CJS vs ESM. So I've kept the `require`s as is.
Consider an `uploadFile` function on the Mux object to save consumers the headache of finding a request library that works well in node for them. Requires more testing and error handling. For now, we're on a time crunch to release the typescript conversion branch which this doc improvement should ideally release with ⏲️ 
This is a [cleaned up version of this …
> [Enhancement] Update docs to reduce ingest friction

- CHANGELOG.md
- src/index.ts
- test/integration/data/errors.spec.js
- test/integration/data/exports.spec.js
- test/integration/data/filters.spec.js
- test/integration/data/incidents.spec.js
- test/integration/data/metrics.spec.js
- test/integration/data/real_time.spec.js
- test/integration/data/video_views.spec.js
- test/integration/video/assets.spec.js
- test/integration/video/deliveryUsage.spec.js
- test/integration/video/liveStreams.spec.js
- test/integration/video/playbackIds.spec.js
- test/integration/video/signingKeys.spec.js
- test/integration/video/uploads.spec.js
Instead of trying to split the difference with a CJS main export, we need to bite the bullet and make it an ESModule export (or else typescript in consuming projects gets _very_ confused).
> esmodule fix + test updates

- src/mux.ts
I broke `new Mux()`. I now unbroke `new Mux()`.
> fixed no-arg Mux ctor

- src/utils/jwt.ts
Previously, `type` in the `MuxJWTSignOptions` interface was set as a
`TypeClaim`. However, wherever this is used, it is expected to be a string and
is mapped to a `TypeClaim`. This is most evident on line 94, where type is
defaulted to `'video'`, not a `TypeClaim`.
> fix(jwt): correct typing for type in MuxJWTSignOptions

- src/data/domain.ts
According to the [document](https://docs.mux.com/api-reference/data#operation/list-breakdown-values), `measurement` param can consume `count` and `sum`.
This PR updates type to allow it.
> fix type of metric's measurement

- src/video/domain.ts
I noticed that, when an asset is created starting from another asset (e.g. when one generates clips), a `source_asset_id` property is present. This PR adds that property to the `Asset` interface.
> Add `source_asset_id` property to Asset interface

- src/video/domain.ts
`embedded_subtitles` should be an optional type when creating a livestream:
> Make embedded_subtitles optional

- src/RequestOptions.ts
- src/base.ts
- test/unit/base.spec.cjs
Adds an optional custom header that users can add to aid in identifying the platform being used to make the request.
```
new Mux(accessToken, secret, { 
platform {
name : 'My Platform',
version '2.0'
}
});
```
> Add custom header for platform identification

- src/utils/jwt.ts
- src/video/domain.ts
- src/video/resources/playbackRestrictions.ts
- src/video/resources/spaces.ts
- src/video/resources/transcriptionVocabularies.ts
- test/unit/mux.spec.cjs
- test/unit/utils/jwt.spec.cjs
This PR addresses https://github.com/muxinc/mux-node-sdk/issues/197 as well as https://github.com/muxinc/mux-node-sdk/pull/194
It fixes the following types:
```
GetAssetPlaybackIdResponse
GetLiveStreamPlaybackIdResponse
PlaybackRestrictionResponse
ListPlaybackRestrictionsResponse
SpaceResponse
BroadcastResponse
ListSpacesResponse 
StartSpaceBroadcastResponse
StopSpaceBroadcastResponse
ListTranscriptionVocabulariesResponse
TranscriptionVocabularyResponse
```
and splits JWT signing into playback Ids and Space Ids for Real Time
> Fix incorrect types and split JWT signing

- package.json
[TS5 and `--moduleResolution bundler`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler) require us to be a little more explicit with our types.
First realized this after [`create-next-app` changed its default `moduleResolution` to `bundler`](https://github.com/vercel/next.js/pull/51957)
The changes in this PR have been tested using `yarn link` against that `create-next-app` repo. VSCode integrations and ts build errors are back!
> Add additional types declaration to package.json

- UPGRADE_8.x.md
This was accidentally removed earlier.
> docs: add upgrade to v8 guide back in

- packages/mcp-server/README.md
Otherwise `npx` will use the cached version until the user explicitly clears their cache.
> Add latest to MCP instructions
