package.json

add engines.node support for node >=8

---

src/utils/api.js

Firebase Cloud Functions fails without this.

Spread operator isn't supported in LTS node

---

README.md

Add JWT examples to readme

---

src/webhooks/webhooks.js

Noticed after reviewing: https://github.com/muxinc/mux-node-sdk/pull/35/files
This can be merged after the above PR is merged.

Updating comment examples for webhooks

---

README.md

We have a similar [example for elixir](https://github.com/muxinc/mux-elixir#verifying-webhook-signatures-in-phoenix)
Using the raw (unparsed) request body can sometimes lead to confusion so including an example is nice

add express.js example to README with webhook signature verification

---

.travis.yml
package.json
src/video/resources/deliveryUsage.js
src/video/resources/liveStreams.js
src/video/video.js
src/webhooks/resources/verify_header.js
test/helper.js
test/integration/video/deliveryUsage.spec.js
test/integration/video/liveStreams.spec.js
test/unit/data/resources/incidents.spec.js
test/unit/video/resources/deliveryUsage.spec.js
test/unit/video/resources/liveStreams.spec.js
test/unit/webhooks/resources/verify_header.spec.js
test/unit/webhooks/webhooks.spec.js

Add entrypoints for Simulcast Targets and DeliveryUsage

---

CHANGELOG.md
README.md
package.json

I already merged #41 (thanks for the review @JacquiManzi!). Now we can release a new minor version.
Also:
* Update README with release steps - did I get these right? I forget, do the docs get updated automatically when merged?

Release 2.6.0

---

src/mux.js

Hackathon student found this bug in the docs

update top level class docs for Mux

---

types/interfaces/CreateUploadParams.ts

Allow new_asset_settings without 'input'

---

CHANGELOG.md
README.md
README_INTERNAL.md
package.json
types/interfaces/CreateLiveStreamParams.ts

- this patch release includes the change from #53 
- adds another Typescript fixe for `new_asset_settings`

release version 3.0.1

---

CHANGELOG.md
package.json

Diff is here - 2 small changes:
https://github.com/muxinc/mux-node-sdk/compare/v3.0.3...master

prep 3.0.4 release

---

CHANGELOG.md
package.json

Diff compare master to 3.0.4: https://github.com/muxinc/mux-node-sdk/compare/v3.0.4...master

prep 3.1.0

---

README_INTERNAL.md
package.json

Changes for 3.1.2:
https://github.com/muxinc/mux-node-sdk/compare/v3.1.1...v3.1.2

Release 3.1.2

---

types/mux.d.ts

* https://github.com/muxinc/mux-node-sdk/commit/3828e48f4d4a8ee3d6fbac7120f236d62e8aa8a3#r46701206
* https://github.com/muxinc/mux-node-sdk/pull/81#discussion_r567160209
This was unintentionally removed in #81

add back Upload.get to typescript defs

---

types/mux.d.ts

ref. https://github.com/muxinc/mux-node-sdk/blob/4659f3409d04ecac0555d9dcf22ac49c4e77f569/src/video/resources/assets.js#L133-L158

Add missing parameter

---

README_INTERNAL.md
package.json

Diff: https://github.com/muxinc/mux-node-sdk/compare/v3.1.3...v3.1.4
1 small typedef fix from #99

Bump for 3.1.4

---

README_INTERNAL.md
package.json

Diff: https://github.com/muxinc/mux-node-sdk/compare/v3.1.4...master
Contains:
- #101 - update docs links to new docs site, add missing `Video.Uploads.get()` function (which was an oversight from before), add `Video.PlaybackIds.get()` (newly released API)
- #102 - dependabot update

release 3.2.0

---

package.json

diff: https://github.com/muxinc/mux-node-sdk/compare/v3.2.0...master
- fix asset clipping params typedef #105 
- bump lodash dependency #32

Bump for 3.2.1

---

types/mux.d.ts

As mentioned in https://github.com/muxinc/mux-node-sdk/issues/124, using this doc page as reference https://hexdocs.pm/mux/Mux.Data.Filters.html#list/1

Fix Filters.list type to reflect what it actually is

---

types/mux.d.ts

- Added new live_stream_id and upload_id params.

Added missing params for List Assets

---

README.md

I have made these badge headers beautiful. Gaze in awe.
(also I'm standardizing them across all the SDKs)

badges + links in readme header

---

src/base.ts
src/mux.ts
src/version.ts
src/video/resources/spaces.ts
test/unit/mux.spec.cjs

Added missing 2-arg ctor overloads

---

.tool-versions
package.json
src/video/domain.ts
test/unit/video/resources/liveStreams.spec.cjs

Add support for reconnect window with slates

---

package.json
src/version.ts
src/video/domain.ts

Add missing fields to `Asset` interface

---

package.json
src/version.ts

Prepare for v6.3.1 release

---

src/mux.ts

Add missing exports, based on report in #192 

Add missing exports

---

README.md
package.json
src/utils/jwt.ts
src/version.ts

Update version for 7.0.0 release

---

src/utils/jwt.ts

Disallow empty Space IDs to be signed

---

package.json
yarn.lock

Update dependencies to address security issues

---

package.json
src/utils/jwt.ts
src/version.ts
test/unit/utils/jwt.spec.cjs

Add helper method to sign viewer count requests

---

src/video/domain.ts

Add resolution_tier and max_resolution_tier

---

package.json

- Adds types for `max_resolution_tier` and `resolution_tier` #314

Bump for 7.3.2

---

README.md

Add section on JWT helpers
